name: ChIPPy
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python=3.8
 - r-base=4.3
 - fastqc
 - trimmomatic
 - bowtie2
 - picard
 - samtools
 - macs2
 - r-tidyverse
 - r-rcolorbrewer
 - bioconductor-diffbind
 - bioconductor-biocparallel
